version: '3.8'
services:
  frontend:
    build:
      context: cbporganizer-frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      REACT_APP_API_URL: ${BACKEND_URL}
    networks:
      - my-network
  backend:
    build:
      context: cbporganizer-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - my-network
networks:
  my-network:
